-- One row per policy document: the table a data steward registers in
-- DataMarket and the table Genie answers "which documents cover X?" from.
-- ai_classify / ai_summarize read only the first few thousand characters so
-- a full refresh stays cheap as the library grows.

CREATE OR REFRESH MATERIALIZED VIEW policy_document_catalog (
  source_file    STRING COMMENT 'SharePoint URL of the source PDF',
  document_title STRING COMMENT 'Readable title derived from the file name',
  policy_domain  STRING COMMENT 'Policy area assigned by ai_classify',
  summary        STRING COMMENT 'Short plain-language summary generated by ai_summarize',
  chunk_count    BIGINT COMMENT 'Number of retrieval chunks for this document',
  char_count     BIGINT COMMENT 'Total characters of extracted text'
)
COMMENT 'Catalog of county policy documents from SharePoint, one row per PDF, with AI-assigned policy domain and summary.'
AS
WITH docs AS (
  SELECT
    source_file,
    COUNT(*)                                        AS chunk_count,
    SUM(LENGTH(chunk))                              AS char_count,
    LEFT(ARRAY_JOIN(COLLECT_LIST(chunk), '\n\n'), 6000) AS opening_text
  FROM rag_docs_chunks
  GROUP BY source_file
)
SELECT
  source_file,
  -- "SLED-008-GIS-Data-Standards.pdf" -> "GIS Data Standards"
  TRIM(REGEXP_REPLACE(
    REGEXP_REPLACE(
      URL_DECODE(REGEXP_EXTRACT(source_file, '([^/]+)\\.pdf$', 1)),
      '^[A-Za-z]+[-_ ]?[0-9]+[-_ ]+', ''
    ),
    '[_-]+', ' '
  ))                                                 AS document_title,
  AI_CLASSIFY(
    opening_text,
    ARRAY(
      'Procurement',
      'Human Resources',
      'Finance and Budget',
      'Public Records',
      'Emergency Management',
      'Information Technology and Security',
      'GIS and Infrastructure',
      'Public Health and Environment',
      'Audit and Compliance',
      'Community Engagement',
      'Fleet and Operations'
    )
  )                                                  AS policy_domain,
  AI_SUMMARIZE(opening_text, 60)                     AS summary,
  chunk_count,
  char_count
FROM docs;
