import React, { useState } from 'react'
import { Bot, Send, Sparkles, Database, BarChart3, Table2, Lightbulb } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'

const sampleQuestions = [
  { icon: BarChart3, text: 'What are the top 5 departments by budget allocation?' },
  { icon: Database, text: 'Show me all flagged vendor payments with their reasons' },
  { icon: Table2, text: 'Which vendors have the highest risk scores?' },
  { icon: BarChart3, text: 'What is the total internal billing by service type?' },
  { icon: Database, text: 'Show budget variance by department' },
  { icon: Table2, text: 'How many LSBE-certified vendors do we have?' }
]

const demoConversation = [
  {
    role: 'user',
    content: 'What are the top 5 departments by budget allocation?'
  },
  {
    role: 'assistant',
    content: 'Here are the top 5 departments by budget allocation for FY2024-25:',
    sql: `SELECT d.department_name, d.budget_allocation
FROM gold_departments d
ORDER BY d.budget_allocation DESC
LIMIT 5`,
    results: [
      { department: 'Health Services', budget: '$5.20B' },
      { department: 'Sheriff', budget: '$3.80B' },
      { department: 'Public Social Services', budget: '$2.90B' },
      { department: 'Mental Health', budget: '$2.20B' },
      { department: 'Children and Family Services', budget: '$1.90B' }
    ]
  }
]

export function AIExplorerPage() {
  const [messages, setMessages] = useState(demoConversation)
  const [input, setInput] = useState('')
  const [isThinking, setIsThinking] = useState(false)

  const handleSend = () => {
    if (!input.trim()) return
    const userMsg = { role: 'user', content: input }
    setMessages(prev => [...prev, userMsg])
    setInput('')
    setIsThinking(true)

    setTimeout(() => {
      setMessages(prev => [...prev, {
        role: 'assistant',
        content: 'This is a demo of the Genie-powered AI Explorer. In production, this would execute SQL against your Gold layer tables and return real results. Connect this to Genie Space ID: 01f1120fc3f810f5bcc1e77f35ad1231',
        sql: '-- Query would be generated by Databricks Genie',
        results: null
      }])
      setIsThinking(false)
    }, 1500)
  }

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ backgroundColor: '#003366' }}>
            <Bot className="h-5 w-5 text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-gray-900">AI Explorer</h2>
            <p className="text-gray-500">Ask questions about County data in natural language — powered by Databricks Genie</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-6">
        <div className="xl:col-span-3 space-y-4">
          <Card className="min-h-[500px] flex flex-col">
            <CardContent className="flex-1 p-4 space-y-4 overflow-y-auto">
              {messages.map((msg, i) => (
                <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[85%] rounded-xl px-4 py-3 ${
                    msg.role === 'user' 
                      ? 'bg-[#003366] text-white' 
                      : 'bg-gray-50 border border-gray-200'
                  }`}>
                    {msg.role === 'assistant' && (
                      <div className="flex items-center gap-2 mb-2">
                        <Sparkles className="h-4 w-4 text-blue-600" />
                        <span className="text-xs font-medium text-blue-600">Genie AI</span>
                      </div>
                    )}
                    <p className={`text-sm ${msg.role === 'user' ? 'text-white' : 'text-gray-800'}`}>
                      {msg.content}
                    </p>
                    {msg.sql && (
                      <div className="mt-3 bg-gray-900 rounded-lg p-3 overflow-x-auto">
                        <div className="flex items-center gap-2 mb-1">
                          <Badge className="bg-blue-600 text-white text-[10px]">SQL</Badge>
                        </div>
                        <pre className="text-xs text-green-400 font-mono whitespace-pre-wrap">{msg.sql}</pre>
                      </div>
                    )}
                    {msg.results && (
                      <div className="mt-3 overflow-x-auto">
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="border-b border-gray-300">
                              {Object.keys(msg.results[0]).map(k => (
                                <th key={k} className="text-left py-2 px-3 font-medium text-gray-500 capitalize">{k}</th>
                              ))}
                            </tr>
                          </thead>
                          <tbody>
                            {msg.results.map((row, ri) => (
                              <tr key={ri} className="border-b border-gray-100">
                                {Object.values(row).map((v, vi) => (
                                  <td key={vi} className="py-2 px-3 text-gray-700">{v}</td>
                                ))}
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                </div>
              ))}
              {isThinking && (
                <div className="flex justify-start">
                  <div className="bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 flex items-center gap-2">
                    <div className="flex gap-1">
                      <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                      <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                      <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                    <span className="text-xs text-gray-500">Genie is thinking...</span>
                  </div>
                </div>
              )}
            </CardContent>

            <div className="border-t p-4">
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="Ask a question about County data..."
                  className="flex-1 px-4 py-2.5 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                  value={input}
                  onChange={e => setInput(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && handleSend()}
                />
                <Button onClick={handleSend} style={{ backgroundColor: '#003366' }}>
                  <Send className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </Card>
        </div>

        <div className="space-y-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm flex items-center gap-2">
                <Lightbulb className="h-4 w-4 text-amber-500" />
                Try asking...
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {sampleQuestions.map((q, i) => (
                <button
                  key={i}
                  onClick={() => setInput(q.text)}
                  className="w-full text-left p-2.5 rounded-lg border border-gray-100 hover:bg-gray-50 hover:border-gray-200 transition-colors group"
                >
                  <div className="flex items-start gap-2">
                    <q.icon className="h-3.5 w-3.5 text-gray-400 mt-0.5 group-hover:text-blue-500" />
                    <span className="text-xs text-gray-600 group-hover:text-gray-900">{q.text}</span>
                  </div>
                </button>
              ))}
            </CardContent>
          </Card>

          <Card className="bg-blue-50 border-blue-200">
            <CardContent className="p-4">
              <div className="flex items-start gap-2">
                <Sparkles className="h-4 w-4 text-blue-600 mt-0.5" />
                <div>
                  <p className="text-xs font-medium text-blue-900">Powered by Databricks Genie</p>
                  <p className="text-xs text-blue-700 mt-1">
                    AI Explorer translates natural language into SQL queries against 6 Gold layer tables 
                    covering budgets, vendors, payments, and internal billing.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
